version: '3.2'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  waypost-client:
    image: waypostio/waypost-client:latest
    restart: always
    depends_on:
      - waypost-server
      - postgres
    ports:
      - "3000:3000"
    stdin_open: true
  waypost-server:
    image: waypostio/waypost-server:latest
    restart: always
    env_file: ./.env
    ports:
      - "5000:5000"
    depends_on:
      - postgres
  waypost-flag-provider:
    image: waypostio/waypost-flag-provider
    env_file: ./.env
    restart: always
    ports:
      - "5050:5050"
    depends_on:
      - waypost-server
      - waypost-client